export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_FOLLOWING_COUNT = 'SET_USER_FOLLOWING_COUNT';
export const SET_USER_FOLLOWER_COUNT = 'SET_USER_FOLLOWER_COUNT';
export const SET_USER_GROUP_COUNT = 'SET_USER_GROUP_COUNT';
